### ISSUE TITLE
favicon now missing from dev server

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-mlhframework#14] opened 2023-10-13 13:57 UTC
The favicon was working on the dev server but is not after the recent framework changes.  Can look into this more next week but figured I'd flag it in case people have thoughts!

**Comment by BryceStevenWilley** [comment] 2023-10-13 14:32
That's weird; the framework was installed on version 0.2.0, but when I downloaded the Zip file of the installed package, the favicon folders just weren't there. Did you install it from the playground? I have a hunch that could be the issue, but I'm not sure.

**Comment by ekressmiller** [comment] 2023-10-13 15:30
I think it was Brett who installed the new version, so sending those questions to you when you have a chance, @normon66

**Comment by normon66** [comment] 2023-10-13 15:43
In preparation to install the security deposit letter last night, I pulled the `main` branch of the framework (which I bumped to 0.2.0 for the recent css changes) into the Playground and installed from there.

**Comment by normon66** [comment] 2023-10-13 16:02
I just needed to make another small change on the framework (removed a 'BH' that I left on a package reference...). This time I updated from the package management page and the favicon persisted, so I think Bryce's assessment that it's a Playground bug is accurate.

**Comment by BryceStevenWilley** [comment] 2023-10-13 20:57
I confirmed that when doing operations from the playground to the server directly, docassemble ignores any files that are nested in the `data/questions`, `data/static`, `data/sources`, `data/templates` folders, which includes our favicon files in `data/static/dev_favicon` and `data/static/prod_favicon`.

A fix would be bigger than I thought, since the playground effectively doesn't know those files exist at all. Unfortunately we either have to only have a single favicon for both the dev and prod servers, or we have to only install from Github, not from the playground. IMO the latter is the better option, even if it takes a bit more time each time we update the server. :/

Gonna close this, since I don't think there's anything actionable here.

**Closed by BryceStevenWilley** 2023-10-13 20:57 UTC
